name: C/C++ CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure
      uses: actions/checkout@v4
    - name: make
<<<<<<< HEAD
      run: make build
=======
      run: make
>>>>>>> d32ec0b8cb10b05e1fd0f0630b369642f6aa59b4
